language: go
sudo: false

# Must generate the parser before installing deps or go get will error out on
# undefined lexer tokens.
before_install:
 - make vm/parser.go

# Default dependency installation command, which is disabled when Makefile
# detected.
install:
 - travis_retry make install_deps

# Run all tests, under race detector.
script: make && go test

# Run tests at these Go versions.  YAML always attempts to autoconvert
# numerics, which famously turns "1.10" into "1.1", so quote all our versions
# here as strings.
go:
  - "tip"
  - "1.10"
  - "1.9"
  - "1.8"

# GOMAXPROCS=1 forces scheduling race bugs.
env:
  - GOMAXPROCS=1
  - GOMAXPROCS=2
  - GOMAXPROCS=4

# Allow tip to fail, and only wait for mature versions to succeed before
# reporting build status.
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
