common-build: &common-build
  working_directory: /go/src/github.com/google/mtail
  environment:
    TEST_RESULTS: /tmp/test-results
  steps:
    - checkout
    - run: mkdir -p $TEST_RESULTS
    - run: go get github.com/jstemmer/go-junit-report
    - run: make vm/parser.go
    - run: make install_coverage_deps
    - run:
        name: Run tests with race detector
        command: |
          trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
          make testrace | tee ${TEST_RESULTS}/go-test.out
    - run:
        name: Run tests with coverage
        command: |
          make gover.coverprofile
          mkdir -p workspace
          cp gover.coverprofile workspace/${CIRCLE_JOB}.coverprofile
    - persist_to_workspace:
        root: workspace
        paths:
          - "*.coverprofile"
    - run: make bench
    - store_test_results:
        path: /tmp/test-results

go1_9: &go1_9
  <<: *common-build
  docker:
    - image: circleci/golang:1.9
go1_8: &go1_8
  <<: *common-build
  docker:
    - image: circleci/golang:1.8
go1_7: &go1_7
  <<: *common-build
  docker:
    - image: circleci/golang:1.7

concurrency_4: &concurrency_4
  environment:
    GOMAXPROCS: 4
concurrency_2: &concurrency_2
  environment:
    GOMAXPROCS: 2
concurrency_1: &concurrency_1
  environment:
    GOMAXPROCS: 1

version: 2
jobs:
  build-go1.9-4:
    <<: [*go1_9, *concurrency_4]
  build-go1.9-2:
    <<: [*go1_9, *concurrency_2]
  build-go1.9-1:
    <<: [*go1_9, *concurrency_1]
  build-go1.8-4:
    <<: [*go1_8, *concurrency_4]
  build-go1.8-2:
    <<: [*go1_8, *concurrency_2]
  build-go1.8-1:
    <<: [*go1_8, *concurrency_1]
  build-go1.7-4:
    <<: [*go1_7, *concurrency_4]
  build-go1.7-2:
    <<: [*go1_7, *concurrency_2]
  build-go1.7-1:
    <<: [*go1_7, *concurrency_1]

  coverage:
    working_directory: /go/src/github.com/google/mtail
    docker:
      - image: circleci/golang:1.9
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: make install_coverage_deps
      - run:
        name: Generate coverage
        command: |
          gover /tmp/workspace
          go tool cover -html=gover.coverprofile -o coverage.html
          goveralls -coverprofile=gover.coverprofile -service=circle-ci
      - store_artifacts:
        path: gover.coverprofile
        destination: coverage
      - store_artifacts:
        path: coverage.html
        destination: coverage


workflows:
  version: 2
  build:
    jobs:
      - build-go1.9-4
      - build-go1.9-2
      - build-go1.9-1
      - build-go1.8-4
      - build-go1.8-2
      - build-go1.8-1
      - build-go1.7-4
      - build-go1.7-2
      - build-go1.7-1
      - coverage:
          requires:
            - build-go1.9-4
            - build-go1.9-2
            - build-go1.9-1
            - build-go1.8-4
            - build-go1.8-2
            - build-go1.8-1
            - build-go1.7-4
            - build-go1.7-2
            - build-go1.7-1
